// frontend/src/components/AssetChart.tsx
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import type { AccountValue } from '../lib/types';

interface AssetChartProps {
  data: AccountValue[];
}

export default function AssetChart({ data }: AssetChartProps) {
  // 格式化数据用于图表显示
  const chartData = data.map((item) => ({
    date: new Date(item.recorded_at).toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' }),
    value: item.total_value,
    cash: item.cash_balance,
    positions: item.positions_value,
  }));

  // 格式化Y轴刻度
  const formatYAxis = (value: number) => {
    if (value >= 1000000) {
      return `$${(value / 1000000).toFixed(1)}M`;
    }
    if (value >= 1000) {
      return `$${(value / 1000).toFixed(0)}K`;
    }
    return `$${value}`;
  };

  // 格式化Tooltip
  const formatTooltip = (value: number, name: string) => {
    return [`$${value.toLocaleString()}`, name === 'value' ? '总资产' : name === 'cash' ? '现金' : '持仓'];
  };

  if (chartData.length === 0) {
    return (
      <div className="h-64 flex items-center justify-center text-text-muted/50">
        暂无数据
      </div>
    );
  }

  return (
    <div className="h-64">
      <ResponsiveContainer width="100%" height="100%">
        <LineChart data={chartData} margin={{ top: 5, right: 30, left: 0, bottom: 5 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
          <XAxis
            dataKey="date"
            stroke="#6b7280"
            fontSize={12}
            tickLine={false}
            axisLine={false}
          />
          <YAxis
            stroke="#6b7280"
            fontSize={12}
            tickLine={false}
            axisLine={false}
            tickFormatter={formatYAxis}
          />
          <Tooltip
            contentStyle={{
              backgroundColor: 'white',
              border: '1px solid #e5e7eb',
              borderRadius: '8px',
            }}
            formatter={formatTooltip}
          />
          <Line
            type="monotone"
            dataKey="value"
            stroke="#1a3d63"
            strokeWidth={2}
            dot={false}
            activeDot={{ r: 4 }}
          />
        </LineChart>
      </ResponsiveContainer>
    </div>
  );
}

// frontend/src/components/AssetChart.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { AccountValue } from '../lib/types';

const props = defineProps<{
  data: AccountValue[];
}>();

const chart = computed(() => {
  if (props.data.length === 0) {
    return { points: '', labels: [] as string[], min: 0, max: 0 };
  }

  const values = props.data.map((item) => item.total_value);
  const min = Math.min(...values);
  const max = Math.max(...values);
  const range = Math.max(max - min, 1);
  const width = 680;
  const height = 220;

  const points = props.data
    .map((item, index) => {
      const x = props.data.length === 1 ? width / 2 : (index / (props.data.length - 1)) * width;
      const y = height - ((item.total_value - min) / range) * (height - 24) - 12;
      return `${x},${y}`;
    })
    .join(' ');

  const labels = props.data.slice(-5).map((item) =>
    new Date(item.recorded_at).toLocaleDateString('zh-CN', { month: 'short', day: 'numeric' }),
  );

  return { points, labels, min, max };
});

function money(value: number) {
  if (value >= 1000000) return `$${(value / 1000000).toFixed(1)}M`;
  if (value >= 1000) return `$${(value / 1000).toFixed(0)}K`;
  return `$${value.toFixed(0)}`;
}
</script>

<template>
  <div v-if="data.length === 0" class="flex h-64 items-center justify-center text-text-muted/60">
    暂无数据
  </div>
  <div v-else class="h-64">
    <div class="mb-2 flex justify-between text-xs text-text-muted">
      <span>{{ money(chart.min) }}</span>
      <span>{{ money(chart.max) }}</span>
    </div>
    <svg viewBox="0 0 680 220" class="h-52 w-full overflow-visible">
      <line x1="0" y1="12" x2="680" y2="12" stroke="#e5e7eb" stroke-dasharray="4 4" />
      <line x1="0" y1="110" x2="680" y2="110" stroke="#e5e7eb" stroke-dasharray="4 4" />
      <line x1="0" y1="208" x2="680" y2="208" stroke="#e5e7eb" stroke-dasharray="4 4" />
      <polyline :points="chart.points" fill="none" stroke="#1a3d63" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" />
    </svg>
    <div class="grid grid-cols-5 text-xs text-text-muted">
      <span v-for="label in chart.labels" :key="label">{{ label }}</span>
    </div>
  </div>
</template>
