// frontend/src/pages/AnalysisPage.vue
<script setup lang="ts">
import { nextTick, ref } from 'vue';
import AppNav from '../components/AppNav.vue';

interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
}

const messages = ref<Message[]>([
  {
    id: '1',
    role: 'assistant',
    content: '你好，我是 AlphaForge 的 AI 投资助手。你可以先在这里记录想分析的标的，后续可以接入真实 AI 分析接口。',
    timestamp: new Date(),
  },
]);
const input = ref('');
const loading = ref(false);
const messagesEnd = ref<HTMLDivElement | null>(null);

async function scrollToBottom() {
  await nextTick();
  messagesEnd.value?.scrollIntoView({ behavior: 'smooth' });
}

async function submit() {
  if (!input.value.trim() || loading.value) return;

  messages.value.push({
    id: Date.now().toString(),
    role: 'user',
    content: input.value.trim(),
    timestamp: new Date(),
  });
  input.value = '';
  loading.value = true;
  await scrollToBottom();

  window.setTimeout(async () => {
    messages.value.push({
      id: (Date.now() + 1).toString(),
      role: 'assistant',
      content: 'AI 分析后端尚未接入。下一步可以把这里连接到 OpenAI API，并结合你的持仓、订单和实时行情做组合分析。',
      timestamp: new Date(),
    });
    loading.value = false;
    await scrollToBottom();
  }, 800);
}

function handleKeydown(event: KeyboardEvent) {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault();
    submit();
  }
}
</script>

<template>
  <div class="flex min-h-screen flex-col bg-white">
    <AppNav />

    <main class="mx-auto flex w-full max-w-4xl flex-1 flex-col">
      <div class="flex-1 overflow-y-auto px-6 py-8">
        <div class="space-y-6">
          <div
            v-for="message in messages"
            :key="message.id"
            class="flex gap-4"
            :class="message.role === 'user' ? 'justify-end' : 'justify-start'"
          >
            <div v-if="message.role === 'assistant'" class="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-primary text-white">
              A
            </div>
            <div
              class="max-w-[80%] rounded-2xl px-5 py-3"
              :class="message.role === 'user' ? 'bg-primary text-white' : 'bg-gray-100 text-text'"
            >
              <p class="whitespace-pre-wrap text-sm leading-relaxed">{{ message.content }}</p>
              <p class="mt-2 text-xs" :class="message.role === 'user' ? 'text-white/60' : 'text-text-muted'">
                {{ message.timestamp.toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }) }}
              </p>
            </div>
            <div v-if="message.role === 'user'" class="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-gray-300 text-white">
              U
            </div>
          </div>

          <div v-if="loading" class="flex justify-start gap-4">
            <div class="flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-full bg-primary text-white">A</div>
            <div class="rounded-2xl bg-gray-100 px-5 py-3 text-sm text-text-muted">正在分析...</div>
          </div>
        </div>
        <div ref="messagesEnd" />
      </div>

      <div class="border-t border-gray-200 px-6 py-4">
        <form class="flex gap-3" @submit.prevent="submit">
          <textarea
            v-model="input"
            rows="1"
            placeholder="输入你的问题..."
            class="min-h-12 max-h-48 flex-1 resize-none rounded-2xl bg-gray-100 px-4 py-3 text-sm transition-all focus:outline-none focus:ring-2 focus:ring-primary/20"
            @keydown="handleKeydown"
          />
          <button
            type="submit"
            :disabled="!input.trim() || loading"
            class="rounded-2xl bg-primary px-5 py-3 text-sm font-medium text-white transition-colors hover:bg-primary-light disabled:cursor-not-allowed disabled:opacity-40"
          >
            发送
          </button>
        </form>
        <p class="mt-3 text-center text-xs text-text-muted">AI 分析功能可作为下一阶段接入真实模型。</p>
      </div>
    </main>
  </div>
</template>

// frontend/src/pages/AnalysisPage.tsx
import { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

interface Message {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
}

export default function AnalysisPage() {
  const navigate = useNavigate();
  const [messages, setMessages] = useState<Message[]>([
    {
      id: '1',
      role: 'assistant',
      content: '你好！我是 AlphaForge 的AI投资助手。我可以帮你分析市场趋势、评估投资组合、提供投资建议。有什么可以帮助你的吗？',
      timestamp: new Date(),
    },
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!input.trim() || isLoading) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: input.trim(),
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, userMessage]);
    setInput('');
    setIsLoading(true);

    // 模拟AI回复（暂时不接入后端）
    setTimeout(() => {
      const aiResponse: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: '感谢你的提问！AI分析功能即将上线，届时我将能够：\n\n• 分析市场趋势和个股表现\n• 评估你的投资组合风险\n• 提供个性化的投资建议\n• 解读财务报表和公司新闻\n\n敬请期待！',
        timestamp: new Date(),
      };
      setMessages((prev) => [...prev, aiResponse]);
      setIsLoading(false);
    }, 1000);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      const formEvent = e as any;
      formEvent.target.form?.requestSubmit();
    }
  };

  const handleLogout = () => {
    localStorage.removeItem('token');
    navigate('/login');
  };

  return (
    <div className="min-h-screen bg-white flex flex-col">
      {/* 顶部导航 */}
      <nav className="border-b border-gray-200 bg-white">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <h1 className="text-xl font-medium text-primary">AlphaForge</h1>
          <div className="flex items-center gap-6">
            <button onClick={() => navigate('/dashboard')} className="text-text-muted hover:text-text transition-colors">
              控制台
            </button>
            <button onClick={() => navigate('/market')} className="text-text-muted hover:text-text transition-colors">
              全球市场
            </button>
            <button className="text-text font-medium">分析</button>
            <button onClick={handleLogout} className="text-text-muted hover:text-text transition-colors">
              退出
            </button>
          </div>
        </div>
      </nav>

      {/* 主聊天区域 */}
      <main className="flex-1 flex flex-col max-w-4xl mx-auto w-full">
        {/* 消息列表 */}
        <div className="flex-1 overflow-y-auto px-6 py-8">
          <div className="space-y-6">
            {messages.map((message) => (
              <div
                key={message.id}
                className={`flex gap-4 ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
              >
                {message.role === 'assistant' && (
                  <div className="w-8 h-8 rounded-full bg-primary flex items-center justify-center flex-shrink-0">
                    <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                    </svg>
                  </div>
                )}
                <div
                  className={`max-w-[80%] rounded-2xl px-5 py-3 ${
                    message.role === 'user'
                      ? 'bg-primary text-white'
                      : 'bg-gray-100 text-text'
                  }`}
                >
                  <p className="whitespace-pre-wrap text-sm leading-relaxed">{message.content}</p>
                  <p
                    className={`text-xs mt-2 ${
                      message.role === 'user' ? 'text-white/60' : 'text-text-muted'
                    }`}
                  >
                    {message.timestamp.toLocaleTimeString('zh-CN', {
                      hour: '2-digit',
                      minute: '2-digit',
                    })}
                  </p>
                </div>
                {message.role === 'user' && (
                  <div className="w-8 h-8 rounded-full bg-gray-300 flex items-center justify-center flex-shrink-0">
                    <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                  </div>
                )}
              </div>
            ))}
            {isLoading && (
              <div className="flex gap-4 justify-start">
                <div className="w-8 h-8 rounded-full bg-primary flex items-center justify-center flex-shrink-0">
                  <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                  </svg>
                </div>
                <div className="bg-gray-100 rounded-2xl px-5 py-3">
                  <div className="flex gap-1">
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                    <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                  </div>
                </div>
              </div>
            )}
          </div>
          <div ref={messagesEndRef} />
        </div>

        {/* 输入框 */}
        <div className="border-t border-gray-200 px-6 py-4">
          <form onSubmit={handleSubmit} className="flex gap-3">
            <div className="flex-1 relative">
              <textarea
                ref={textareaRef}
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={handleKeyDown}
                placeholder="输入你的问题..."
                rows={1}
                className="w-full px-4 py-3 bg-gray-100 rounded-2xl resize-none focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all text-sm"
                style={{
                  minHeight: '48px',
                  maxHeight: '200px',
                  overflow: 'auto',
                }}
              />
            </div>
            <button
              type="submit"
              disabled={!input.trim() || isLoading}
              className="px-5 py-3 bg-primary hover:bg-primaryLight text-white rounded-2xl transition-colors disabled:opacity-40 disabled:cursor-not-allowed flex items-center gap-2"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
              </svg>
              <span className="text-sm font-medium">发送</span>
            </button>
          </form>
          <p className="text-xs text-text-muted text-center mt-3">
            AI 分析功能即将上线，敬请期待
          </p>
        </div>
      </main>
    </div>
  );
}
